Feature/json retcon
dpla/ingestion3 pull request #499
Opened 2022-07-20 15:56 UTC by mdellabitta

2022-07-20 15:59 UTC, moltude commented on src/main/scala/dpla/ingestion3/mappers/providers/JsonRetconMapper.scala
> +      if (begin.nonEmpty && end.nonEmpty && displayDate.nonEmpty) None
Shouldn't this be `isEmpty`?

2022-07-20 16:00 UTC, moltude commented on src/main/scala/dpla/ingestion3/mappers/providers/JsonRetconMapper.scala
> +  override def place(data: Document[JValue]): ZeroToMany[DplaPlace] =
Don't we want to map coordinates where they existing in the sourceResouce data?

2022-07-20 16:03 UTC, moltude commented on src/test/resources/json-retcon/washington.json
> +    "originalRecord": "http://ldp.dp.la/ldp/original_record/a2a415d0f3030e86e0349f90747d1c86.xml",
SMH

2022-07-20 16:17 UTC, moltude commented on src/main/scala/dpla/ingestion3/mappers/providers/JsonRetconMapper.scala
> +    data.get \ "_source" \ "@id" match {
`@id` is already the full item path. if you want to construct is use `id` or reuse the entire `@id` prop

```  
_source": {
    "@id": "http://dp.la/api/items/8bca6ea2341791bb4b30c471115e76e8",
    "id": "8bca6ea2341791bb4b30c471115e76e8"
}
```
See 
https://raw.githubusercontent.com/dpla/ingestion3/88eca3ec32ba871ec1de2023a16a36addff557dc/src/test/resources/json-retcon/lc.json

2022-07-20 16:20 UTC, moltude commented on src/main/scala/dpla/ingestion3/mappers/providers/JsonRetconMapper.scala
> +      ("dplaId", extractString(data.get \ "_source" \ "id").getOrElse(""))
There should be no `.getOrElse` on this -- we want the extraction on the jsonlRecord() method to fail if the value is not provided and empty string will validate.

2022-07-20 16:21 UTC, moltude requested changes
A couple of issues/questions on this

2022-07-20 16:38 UTC, mdellabitta commented on src/main/scala/dpla/ingestion3/mappers/providers/JsonRetconMapper.scala
> +      if (begin.nonEmpty && end.nonEmpty && displayDate.nonEmpty) None
Lolz. Nice catch!

2022-07-26 05:25 UTC, moltude approved these changes

2022-07-26 13:19 UTC, merged